### ISSUE TITLE
Support channel-specific scaling factors

### ISSUE THREAD

**Issue by tstenner** [bids-standard/pybv#12]
The brainvision format allows each channel to have its own scaling factor, e.g.

```
; Each entry: Ch<Channel number>=<Name>,<Reference channel name>,<Resolution in "Unit">,<Unit>, Future extensions..
Ch1=Fp1,,0.2,µV
Ch2=Fp2,,6.5,nV
```

This is really useful with int16 as datatype since it maximizes each channel's range without impairing precision too much (and it's also what BrainVision Analyzer does).

The only required (backwards compatible) change in the interface would be in the `resolution` parameter, which could either accept `float` array with `nchan` elements or a single `float` that gets promoted automatically.

**Comment by sappelhoff** [comment]
Sounds reasonable, a PR would be welcome!
