### ISSUE TITLE
potential indexing issue

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/pybv#27]
Could it be that we have an indexing issue in our code?

BrainVision uses 1-based indexing for writing the events, whereas in Python and MNE-Python, we use 0-based indexing.

Now imagine a user passing `events`: https://github.com/bids-standard/pybv/blob/cf8aa9d6904149d68ad9d9500315db5e785664a2/pybv/io.py#L46-L50

These events will most likely be 0-indexed.

However, later down in the code -when we write a VMRK file, we translate these indices one to one, disregarding that BrainVision used 1-based indexing. See: https://github.com/bids-standard/pybv/blob/cf8aa9d6904149d68ad9d9500315db5e785664a2/pybv/io.py#L163-L167

Later on in the testing, we actually see this issue: https://github.com/bids-standard/pybv/blob/cf8aa9d6904149d68ad9d9500315db5e785664a2/pybv/tests/test_bv_writer.py#L95-L96

note the comment. I may be wrong ... but it seems to me we should handle the indexing better

cc @tstenner @choldgraf

**Comment by choldgraf** [comment]
ah this does seem like a potential problem - I wonder why we'd be testing for "within one" instead of "exactly the same" in the events...

**Comment by sappelhoff** [comment]
MNE also documents that BrainVision is 1-indexed (not 0-indexed):

https://github.com/mne-tools/mne-python/blob/033f8c13fb03772c26142a1782c18a2a65dc9e8e/mne/io/brainvision/brainvision.py#L219

**Comment by sappelhoff** [comment]
I got a reply from Brain Products:

```
Dear Stefan,

yes, this is correct, BrainVision indexing starts with 1, not with zero (comparable to Matlab indexing as opposed to Python). This means the index of the first data point is 1 and a marker on the first data point would have the position 1, accordingly.
Thank you for noticing that this is not documented in the specifications, I will pass on this information.

Best wishes,
Laura

```
