### ISSUE TITLE
Use "real" testing data from the wild

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/pybv#4]
For future reference, we can use this dataset (CC0 license):

https://zenodo.org/record/20044

**Comment by choldgraf** [comment]
Or whenever the datasets for the EEG and iEEG extensions get released, we can use that data too!

**Comment by sappelhoff** [comment]
Given that we do not (currently) plan to implement a READER in pybv, I am closing this.

For reading, `mne` should be used.
