### ISSUE TITLE
switch to f-strings

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/pybv#54]
We now require Python 3.6 for pybv and we can thus switch to using fstrings like: `print(f"this nice value: {value}")` instead of `print("this nice value: {}".format(value))`

@hoechenberger and I think that that'll make the codebase more readable.

**Comment by cbrnr** [comment]
Absolutely! It's not possible/feasible to use f-strings all the time, but in 99% of all cases this makes sense.

**Comment by hoechenberger** [comment]
+1
