### ISSUE TITLE
pip PyBV --> pybv

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/pybv#6]
The current pip package `PyBV` should be renamed to `pybv` according to pep8 convention and to be consistent with `pyedf`, see: https://github.com/bids-standard/pyEDF/issues/5

Also, the contents of this repo and the `PyBV` package are not congruent, this is something to be solved soonish in order to avoid confusion.

- [x] remove `install_requires` from setup.py, because it's easier if people install numpy themselves (more flexibility)
- [x] discuss licensing
- [x] set Maintainer and Maintainer Email
- [x] update `.gitignore` to exclude `build` and `/dist`
- [x] check how the rendering of README etc. works on test.pypi: https://test.pypi.org/project/pybv/
- [x] update version to 0.0.1 
- [ ] make a "release" on github
- [ ] upload to pypi
- [ ] add other contributors as maintainers
- [ ] add pypi badge and pypi download stats badge (https://pepy.tech/)
- [ ] deal with #3 by pip installing in the circleci config

**Comment by choldgraf** [comment]
totally agree - we should do this whenever we make a pip release for pybv...who controls the pip page for pyBV?

**Comment by sappelhoff** [comment]
Philip Alday :-)

**Comment by sappelhoff** [comment]
thanks @palday!

@choldgraf, I have uploaded a test to `test.pypi`, see: https://test.pypi.org/project/pybv/

I have entered myself as the maintainer for now - if we do the real upload to pypi, should we create a shared bids-community account? Personally I would prefer if one of us takes the responsibility and hands over whenever a successor is needed and available

**Comment by choldgraf** [comment]
@sappelhoff that works for me! Agree that it's good to keep things explicit, so long as it's clear that the tool is technically "owned" by the community, and that any specific maintainer has the right to step away from core maintenance privileges!
