### ISSUE TITLE
Rename master -> main

### ISSUE THREAD

**Issue by cbrnr** [bids-standard/pybv#71]
Eventually we should rename our main development branch. It's not a big deal, we just did it for mne-python.

**Comment by hoechenberger** [comment]
+5000 :)

**Comment by sappelhoff** [comment]
:+1: Please go ahead and do it @cbrnr I found it very easy to follow in mne-python.

**Comment by cbrnr** [comment]
I don't have permissions to change branch names.

**Comment by sappelhoff** [comment]
> I don't have permissions to change branch names.

now you do, .. with great power, .. and so on :)

**Comment by cbrnr** [comment]
Done! Note that I had to reset the remote HEAD (to `main`) in my local clone - see e.g. https://stackoverflow.com/a/49560949/1112283.

**Comment by sappelhoff** [comment]
thanks @cbrnr
