### ISSUE TITLE
Allow event durations == 0

### ISSUE THREAD

**Issue by cbrnr** [bids-standard/pybv#94]
@sappelhoff you recently introduced a bunch of tests in v0.7.3, among others event durations must be >= 1. However, I frequently have annotations that have no duration (i.e. == 0), which previously could be written. Do you have a reason why you want to enforce durations >= 1?

In a similar vain, #93 seems to be the result of another test that might be to strict.

**Comment by sappelhoff** [comment]
Hi Clemens - it seems like this is a mistake, the format spec clearly allows for >= 0, not > 0, see:

https://www.brainproducts.com/download/specification-of-brainvision-core-data-format-1-0/

![image](https://user-images.githubusercontent.com/9084751/177116827-c03d63fb-f13c-4a68-aba2-54a372efe284.png)


However note:

![image](https://user-images.githubusercontent.com/9084751/177116856-bfbf5999-de9c-4a1e-bf24-d66f23ff2ac2.png)


a PR to fix this is welcome!
